AUTHOR_NAME="Jérémie DECOCK"
AUTHOR_EMAIL="jd.jdhp@gmail.com"
AUTHOR_WEB_SITE="www.jdhp.org"

COPYRIGHT_NOTICE="Copyright (c) 2016,2017 ${AUTHOR_NAME} (${AUTHOR_WEB_SITE})"

DOCUMENT_DATE="26 avril 2017"
INSTITUTE=""
DOCUMENT_SUBJECT="La correction orthographique avec les notebooks Jupyter et IPython"
DOCUMENT_KEYWORDS="jupyter,notebook,orthographe"

DOCUMENT_TITLE="La correction orthographique avec les notebooks Jupyter et IPython"
DOCUMENT_SUBTITLE="Installation et configuration"
DOCUMENT_FILE_BASE_NAME="notebook_spellcheck_fr"

DOCUMENT_GIT_FORGE_ACCOUNT="jdhp-docs"
DOCUMENT_GIT_FORGE_REPOSITORY_NAME="notebook-spellcheck"

DOCUMENT_GIT_FORGE_DOMAIN="github.com"
DOCUMENT_GIT_FORGE_URL="https://${DOCUMENT_GIT_FORGE_DOMAIN}"
DOCUMENT_GIT_FORGE_PROJECT_URL="${DOCUMENT_GIT_FORGE_URL}/${DOCUMENT_GIT_FORGE_ACCOUNT}/${DOCUMENT_GIT_FORGE_REPOSITORY_NAME}"
DOCUMENT_ISSUE_TRACKER_URL="${DOCUMENT_GIT_FORGE_URL}/${DOCUMENT_GIT_FORGE_ACCOUNT}/${DOCUMENT_GIT_FORGE_REPOSITORY_NAME}/issues"

DOCUMENT_WEB_SITE_URL="http://www.jdhp.org/documentation_fr.html#${DOCUMENT_FILE_BASE_NAME}"
DOCUMENT_HTML_URL="http://www.jdhp.org/docs/${DOCUMENT_FILE_BASE_NAME}/${DOCUMENT_FILE_BASE_NAME}.html"
DOCUMENT_PDF_URL="http://www.jdhp.org/dl/pdf/${DOCUMENT_FILE_BASE_NAME}.pdf"

HTML_TMP_DIR="html_tmp"
